name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GETNOTER_COM_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_ADDRESS >> ~/.ssh/known_hosts
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: pocolifo/noter-landing-page
          ssh-key: ${{ secrets.GETNOTER_COM_SSH_PRIVATE_KEY }}
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      
      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy static site to server
        run: |
          ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_ADDRESS 'cd html && rm -rf *'
          sftp -i ~/.ssh/id_rsa $SSH_USER@$SSH_ADDRESS:/home/$SSH_USER/html <<< "put dist/**"